ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.application.bibleapp.server.ApplicationKt.module ]
    }
}

jwt {
    secret = "changeme-dev-secret"
    secret = ${?JWT_SECRET}
    issuer = "bibleapp-server"
    audience = "bibleapp-users"
    realm = "BibleApp"
}

storage {
    jdbcUrl = "jdbc:postgresql://localhost:5432/bibleapp"
    jdbcUrl = ${?DATABASE_URL}
    driverClassName = "org.postgresql.Driver"
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "postgres"
    password = ${?DATABASE_PASSWORD}
}
